language: c
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
  # Install nim
  - git clone -b devel git://github.com/nim-lang/Nim.git --depth 1
  - cd Nim
  - git clone -b devel --depth 1 git://github.com/nim-lang/csources
  - cd csources && sh build.sh
  - cd ..
  - bin/nim c koch
  - ./koch boot -d:release
  - export PATH=$PWD/bin:$PATH
  - nim install_nimble.nims
  - cd ..
  - nimble install -y
script:
  - nim test
  