language: c
compiler:
  - gcc
sudo: required
before_install:
  # Install 
  sudo apt-get install java
  # Install nim
  - git clone -b devel git://github.com/nim-lang/Nim.git --depth 1
  - cd Nim
  - git clone -b devel --depth 1 git://github.com/nim-lang/csources
  - cd csources && sh build.sh
  - cd ..
  - bin/nim c koch
  - ./koch boot -d:release
  - export PATH=$PWD/bin:$PATH
  - nim install_nimble.nims
  - cd ..
  - nimble install -y
script:
  - nim test
  